### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by rfeie** [minamarkham/formation#8]
Hi There!

I love the script and am adapting a version for myself but I was trying to figure out why the script uninstalls `brew-cask`. I am sorry to bug you about this and I apologize if an issue is not the correct way to reach out.
Link to the start of the uninstalling:
https://github.com/minamarkham/formation/blob/e337cfe7b43c390874d82a9aacf0302d0219a1dc/slay#L131

Thanks!

**Comment by fractaledmind** [comment]
So I'm going to try and answer the question for @minamarkham. 

First, just to be explicit about what the script is doing at this point: it lists out all of the packages `brew` has installed on your system via `brew list`, it then pipes that list to `grep` to see if the `brew-cask` package is one of them (with the `-F` and `-q` options turned on, which can be expanded to `--fixed-strings` and `--quiet`, meaning the grep search interprets "brew-cask" as a string and not a regular expression and it doesn't report any errors to STDOUT). Only if it finds `brew-cask` in the list of installed packages does it uninstall that package.

It deletes the `brew-cask` package because starting with `brew` version 1.0.0, `brew-cask` was integrated into `brew` directly and thus that package is no longer needed (see [this PR](https://github.com/Homebrew/brew/pull/725))

I hope that helps explaining the reasoning here 😄

**Comment by rfeie** [comment]
It does! In fact it perfectly answers my question. Just wanted to know the reason for `brew-cask` being uninstalled but it is an incredibly hard thing to google (at least for me). Thanks so much!
